version: "3"
services:
  move-worker:
    image: linuxserver/ffmpeg:latest
    container_name: sub_move_worker
    restart: unless-stopped
    entrypoint: /bin/bash /script/move_sync.sh
    environment:
      - PUID=0 #根据情况自行修改
      - PGID=0 #根据情况自行修改
      - TZ=Asia/Shanghai
    volumes:
      - /volume2/media/整理目录:/source #监控目录。请自行修改
      - /volume2/media/上传目录:/dest #目标目录。请自行修改
      - ./move_sync.sh:/script/move_sync.sh
